### ISSUE TITLE
Add ability to set independent endpoints on balancer

### ISSUE THREAD

**Issue by lesaux** [clicman/rancher-cli-addons#3]
I'm not sure I understand the "add-link" action.

I have an existing loadbalancer, and I'd like to add a new "target" (as it's called in webui) to stack=stack1 service=service1 and with a domain (requestHost) of thisismyservice.example.com.

If I understand correctly I should then use 
`--host=stack1.service1.thisismyservice.example.com`

This ends up creating the new target but with `stack1.service1.thisismyservice.example.com` as a request host.

Also, the requestPort is mandatory, whereas it isn't in the webui (if not specified it applies to all ports).

Support for requestPath would be nice too!

It might make things more clear to use the same naming convention as the webUi.

Nevertheless this addon looks useful! keep up the good work.

**Comment by clicman** [comment]
Hi! I see two problems here. 
1. Wrong naming.
 Your target should be service1.stack1.example.com from inner to outer. This is important because cli parses the url to find out which service to bind to balancer.
2. You really want to use independent fqdn in targets but it is impossible for now.

As this cli was initially purposed as staging tool it not support free domain naming. I will analyze it and try to add this option for you.

Also about ports. It you not set port in UI it will balanced to default target port (it applies for http/https targets only). I've created separate issue for it: #4

**Comment by clicman** [comment]
I've performed analysis and decided to not change ideology. Because whole project depends on service.stack.somedomain naming conventions. 
Try [this](https://github.com/rancher/cli/releases) cli instead. Here is a video how to use it: https://www.youtube.com/watch?v=6vtY_4vNvpE
